from __future__ import annotations

from copy import deepcopy
from typing import Any, cast

from app.schemas.models import HardwareSnapshot
from app.services.compatibility import evaluate_compatibility

SEED_HARDWARE = {
    "cpu": {"name": "AMD Ryzen 9 7950X", "cores": 16, "usagePercent": 38, "temperatureC": 61},
    "gpu": {
        "name": "NVIDIA RTX 4090",
        "vendor": "NVIDIA",
        "usagePercent": 46,
        "temperatureC": 68,
        "vramTotalMb": 24576,
        "vramUsedMb": 11320,
        "driverVersion": "560.94",
    },
    "ram": {"totalMb": 65536, "usedMb": 27480},
    "disk": {"totalGb": 2048, "freeGb": 842, "installPathFreeGb": 318},
    "timestamp": "2026-05-10T10:33:00.000Z",
}

VISUALS = {
    "llm": ("/assets/projects/local-llm.jpg", "66% 48%", "#1f8c86", "#0a2f31"),
    "vision": ("/assets/projects/vision-lab.jpg", "62% 72%", "#0284c7", "#061f35"),
    "spark-llm": ("/assets/projects/spark-llm.jpg", "62% 48%", "#1d4ed8", "#071936"),
    "nvidia-blueprint": ("/assets/projects/nvidia-blueprint.jpg", "54% 50%", "#22c55e", "#052e16"),
    "embedding": ("/assets/projects/embedding-foundry.jpg", "64% 48%", "#31a8de", "#08283b"),
    "speech": ("/assets/projects/embedding-foundry.jpg", "42% 48%", "#2563eb", "#071936"),
    "tooling": ("/assets/projects/local-llm.jpg", "48% 50%", "#0f766e", "#062827"),
}

PROJECT_ROWS = [
    (
        "local-llm-studio",
        "Local LLM Studio",
        "llm",
        "Serve Llama, Qwen, DeepSeek and GGUF models.",
        ["gguf", "llama.cpp", "chat"],
        "#5eead4",
        "installed",
        "running",
        8,
        16,
        8,
        24,
        True,
        "Qwen 14B Q4_K_M",
        "main",
        7860,
        "72.4 tok/s",
        "TTFT 410 ms",
        72.4,
        410,
        14820,
    ),
    (
        "vision-lab",
        "Vision Lab",
        "vision",
        "Detection, segmentation and captioning pipelines.",
        ["yolo", "sam", "caption"],
        "#22d3ee",
        "installed",
        "stopped",
        6,
        12,
        6,
        18,
        True,
        "Realtime 1080p",
        "stable",
        8077,
        "58 FPS",
        "p95 34 ms",
        58,
        34,
        10450,
    ),
    (
        "spark-llm-runner",
        "Spark LLM Runner",
        "spark-llm",
        "Batch LLM inference through Spark jobs.",
        ["spark", "batch", "etl"],
        "#2563eb",
        "not_installed",
        "stopped",
        12,
        32,
        12,
        96,
        True,
        "Single node executor",
        "main",
        9091,
        "1.9k rows/min",
        "job p95 8.6s",
        1900,
        8600,
        18600,
    ),
    (
        "nvidia-blueprint-rag",
        "NVIDIA Blueprint RAG",
        "nvidia-blueprint",
        "Containerized RAG blueprint with vector store.",
        ["nvidia", "rag", "containers"],
        "#4ade80",
        "failed",
        "error",
        12,
        48,
        22,
        220,
        True,
        "Blueprint default",
        "release/2.x",
        8010,
        "Service failed",
        "VRAM gate",
        None,
        None,
        22600,
    ),
    (
        "embedding-foundry",
        "Embedding Foundry",
        "embedding",
        "Local embedding benchmark and vector profiles.",
        ["embedding", "vector", "batch"],
        "#38bdf8",
        "not_installed",
        "stopped",
        4,
        8,
        2,
        12,
        False,
        "bge-m3 batch 64",
        "main",
        8120,
        "1.2k vec/s",
        "batch 64",
        1200,
        None,
        3980,
    ),
    (
        "qwen-edge-server",
        "Qwen Edge Server",
        "llm",
        "Run Qwen edge profiles with API routing.",
        ["qwen", "edge", "api"],
        "#14b8a6",
        "installed",
        "stopped",
        8,
        24,
        10,
        42,
        True,
        "Qwen2.5 14B edge",
        "main",
        8211,
        "61 tok/s",
        "TTFT 520 ms",
        61,
        520,
        9216,
    ),
    (
        "llama-router-farm",
        "Llama Router Farm",
        "llm",
        "Route chat traffic across GGUF workers.",
        ["llama", "router", "workers"],
        "#2dd4bf",
        "not_installed",
        "stopped",
        10,
        32,
        12,
        64,
        True,
        "Router balanced",
        "main",
        8212,
        "184 req/min",
        "p95 1.8s",
        184,
        1800,
        11264,
    ),
    (
        "deepseek-code-bench",
        "DeepSeek Code Bench",
        "llm",
        "Benchmark coding models against repo prompts.",
        ["code", "eval", "deepseek"],
        "#60a5fa",
        "installed",
        "running",
        12,
        32,
        16,
        90,
        True,
        "Repo coding suite",
        "stable",
        8213,
        "43 pass@1",
        "batch 128",
        43,
        None,
        14336,
    ),
    (
        "mixtral-quant-lab",
        "Mixtral Quant Lab",
        "llm",
        "Compare MoE quant profiles.",
        ["mixtral", "moe", "quant"],
        "#22c55e",
        "not_installed",
        "stopped",
        14,
        48,
        20,
        120,
        True,
        "MoE Q4 sweep",
        "main",
        8214,
        "37 tok/s",
        "VRAM 18 GB",
        37,
        None,
        18432,
    ),
    (
        "camera-qa-studio",
        "Camera QA Studio",
        "vision",
        "Inspect camera frames with caption review.",
        ["camera", "qa", "caption"],
        "#22d3ee",
        "installed",
        "stopped",
        6,
        16,
        8,
        28,
        True,
        "Realtime QA",
        "stable",
        8221,
        "42 FPS",
        "p95 44 ms",
        42,
        44,
        7168,
    ),
    (
        "defect-vision-cell",
        "Defect Vision Cell",
        "vision",
        "Detect manufacturing defects from images.",
        ["defect", "yolo", "batch"],
        "#0ea5e9",
        "not_installed",
        "stopped",
        8,
        24,
        10,
        60,
        True,
        "Factory batch",
        "main",
        8222,
        "310 img/min",
        "mAP 0.72",
        310,
        None,
        9216,
    ),
    (
        "ocr-layout-forge",
        "OCR Layout Forge",
        "vision",
        "Parse screenshots and PDF layout regions.",
        ["ocr", "layout", "pdf"],
        "#2dd4bf",
        "installed",
        "stopped",
        6,
        16,
        6,
        32,
        True,
        "Document layout",
        "main",
        8223,
        "96 pages/min",
        "p95 620 ms",
        96,
        620,
        5120,
    ),
    (
        "sam-desk-segmenter",
        "SAM Desk Segmenter",
        "vision",
        "Segment objects from screenshots.",
        ["sam", "segment", "mask"],
        "#38bdf8",
        "not_installed",
        "stopped",
        8,
        24,
        12,
        72,
        True,
        "SAM desktop",
        "main",
        8224,
        "28 masks/s",
        "batch 16",
        28,
        None,
        10240,
    ),
    (
        "spark-rag-indexer",
        "Spark RAG Indexer",
        "spark-llm",
        "Build vector indexes with Spark executors.",
        ["spark", "rag", "index"],
        "#2563eb",
        "installed",
        "stopped",
        12,
        48,
        12,
        160,
        True,
        "Index workers",
        "main",
        8231,
        "5.8k docs/min",
        "8 workers",
        5800,
        None,
        11264,
    ),
    (
        "batch-eval-orchestrator",
        "Batch Eval Orchestrator",
        "spark-llm",
        "Queue prompt eval jobs.",
        ["eval", "spark", "queue"],
        "#38bdf8",
        "not_installed",
        "stopped",
        12,
        48,
        16,
        140,
        True,
        "Eval queue",
        "main",
        8232,
        "2.4k rows/min",
        "p95 7.1s",
        2400,
        7100,
        15360,
    ),
    (
        "dataset-distill-runner",
        "Dataset Distill Runner",
        "spark-llm",
        "Distill corpora into instruction datasets.",
        ["distill", "dataset", "etl"],
        "#0ea5e9",
        "installed",
        "running",
        16,
        64,
        20,
        220,
        True,
        "Distill pass",
        "stable",
        8233,
        "820 pairs/min",
        "job p95 11s",
        820,
        11000,
        19456,
    ),
    (
        "triton-blueprint-serve",
        "Triton Blueprint Serve",
        "nvidia-blueprint",
        "Serve TensorRT engines with Triton.",
        ["triton", "tensorrt", "serve"],
        "#4ade80",
        "not_installed",
        "stopped",
        16,
        64,
        18,
        180,
        True,
        "Triton single GPU",
        "release/1.x",
        8241,
        "710 infer/s",
        "p95 24 ms",
        710,
        24,
        17408,
    ),
    (
        "cuda-agent-workshop",
        "CUDA Agent Workshop",
        "nvidia-blueprint",
        "Prototype GPU agent tools.",
        ["cuda", "agent", "telemetry"],
        "#22c55e",
        "installed",
        "stopped",
        12,
        48,
        14,
        120,
        True,
        "Agent lab",
        "main",
        8242,
        "94 tasks/min",
        "VRAM 12 GB",
        94,
        None,
        12288,
    ),
    (
        "nemo-guardrail-stack",
        "NeMo Guardrail Stack",
        "nvidia-blueprint",
        "Run local guardrail services.",
        ["nemo", "guardrail", "policy"],
        "#16a34a",
        "not_installed",
        "stopped",
        10,
        32,
        10,
        96,
        True,
        "Policy suite",
        "main",
        8243,
        "390 checks/min",
        "p95 180 ms",
        390,
        180,
        9216,
    ),
    (
        "vector-recall-bench",
        "Vector Recall Bench",
        "embedding",
        "Measure recall across vector stores.",
        ["vector", "recall", "bench"],
        "#38bdf8",
        "installed",
        "stopped",
        6,
        16,
        4,
        44,
        False,
        "Recall sweep",
        "main",
        8251,
        "14k q/min",
        "recall 0.91",
        14000,
        None,
        3072,
    ),
    (
        "reranker-arena",
        "Reranker Arena",
        "embedding",
        "Compare local rerankers for RAG quality.",
        ["rerank", "rag", "score"],
        "#0ea5e9",
        "not_installed",
        "stopped",
        8,
        24,
        8,
        58,
        True,
        "Rerank suite",
        "main",
        8252,
        "1.1k pairs/s",
        "nDCG 0.84",
        1100,
        None,
        7168,
    ),
    (
        "multilingual-speech-lab",
        "Multilingual Speech Lab",
        "speech",
        "Transcribe multilingual audio batches.",
        ["whisper", "speech", "align"],
        "#60a5fa",
        "installed",
        "stopped",
        8,
        24,
        8,
        80,
        True,
        "Whisper large",
        "main",
        8261,
        "18x realtime",
        "WER 7.4",
        18,
        None,
        7168,
    ),
    (
        "voice-clone-sandbox",
        "Voice Clone Sandbox",
        "speech",
        "Experiment with local voice profiles.",
        ["voice", "tts", "sandbox"],
        "#2563eb",
        "not_installed",
        "stopped",
        10,
        32,
        12,
        110,
        True,
        "TTS lab",
        "main",
        8262,
        "31 clips/min",
        "p95 2.2s",
        31,
        2200,
        11264,
    ),
    (
        "audio-diarization-node",
        "Audio Diarization Node",
        "speech",
        "Split speaker turns for meetings.",
        ["diarize", "speaker", "timeline"],
        "#38bdf8",
        "installed",
        "stopped",
        8,
        16,
        6,
        48,
        True,
        "Speaker timeline",
        "main",
        8263,
        "9.8x realtime",
        "DER 6.2",
        9.8,
        None,
        5120,
    ),
    (
        "promptops-control-plane",
        "PromptOps Control Plane",
        "tooling",
        "Track prompts and endpoint health.",
        ["promptops", "config", "health"],
        "#0f766e",
        "installed",
        "running",
        4,
        8,
        0,
        16,
        False,
        "Control plane",
        "main",
        8271,
        "12 endpoints",
        "live sync",
        12,
        None,
        1024,
    ),
    (
        "model-cache-manager",
        "Model Cache Manager",
        "tooling",
        "Clean and move model caches.",
        ["cache", "models", "disk"],
        "#0284c7",
        "installed",
        "stopped",
        4,
        8,
        0,
        20,
        False,
        "Cache audit",
        "main",
        8272,
        "318 GB free",
        "scan 9s",
        318,
        9000,
        1024,
    ),
    (
        "agent-runbook-studio",
        "Agent Runbook Studio",
        "tooling",
        "Manage repeatable agent runbooks.",
        ["agent", "runbook", "health"],
        "#22c55e",
        "not_installed",
        "stopped",
        4,
        8,
        0,
        18,
        False,
        "Runbook base",
        "main",
        8273,
        "42 runs/day",
        "success 96%",
        42,
        None,
        1024,
    ),
    (
        "gpu-observability-lite",
        "GPU Observability Lite",
        "tooling",
        "Sample GPU process metrics.",
        ["gpu", "metrics", "dash"],
        "#38bdf8",
        "installed",
        "running",
        4,
        8,
        0,
        12,
        False,
        "Telemetry agent",
        "main",
        8274,
        "1s samples",
        "4 streams",
        4,
        1000,
        1024,
    ),
    (
        "semantic-cache-proxy",
        "Semantic Cache Proxy",
        "embedding",
        "Cache similar prompt responses.",
        ["cache", "embedding", "proxy"],
        "#22c55e",
        "not_installed",
        "stopped",
        6,
        16,
        4,
        36,
        False,
        "Cache proxy",
        "main",
        8253,
        "87% hits",
        "p95 42 ms",
        87,
        42,
        3072,
    ),
    (
        "bluegreen-deploy-gateway",
        "Bluegreen Deploy Gateway",
        "tooling",
        "Switch provider endpoint slots.",
        ["deploy", "gateway", "routing"],
        "#38bdf8",
        "installed",
        "stopped",
        4,
        8,
        0,
        24,
        False,
        "Bluegreen routes",
        "main",
        8275,
        "24 routes",
        "swap 3s",
        24,
        3000,
        1024,
    ),
]


def provider_seed() -> list[dict]:
    hardware = HardwareSnapshot.model_validate(SEED_HARDWARE)
    providers = []
    for row in PROJECT_ROWS:
        (
            provider_id,
            name,
            project_type,
            description,
            tags,
            accent_color,
            install_status,
            run_status,
            cpu_cores,
            ram_gb,
            vram_gb,
            disk_gb,
            gpu_required,
            profile,
            branch,
            port,
            headline,
            secondary,
            throughput,
            latency_ms,
            vram_peak_mb,
        ) = row
        image_url, focus, ambient, ambient_soft = VISUALS[project_type]
        provider = {
            "id": provider_id,
            "name": name,
            "type": project_type,
            "repoUrl": f"https://github.com/ntc-ai/{provider_id}",
            "description": description,
            "tags": tags,
            "accentColor": accent_color,
            "visual": {"imageUrl": image_url, "focus": focus, "ambient": ambient, "ambientSoft": ambient_soft},
            "installStatus": install_status,
            "runStatus": run_status,
            "requirements": {
                "minimum": {
                    "cpuCores": cpu_cores,
                    "ramMb": ram_gb * 1024,
                    "vramMb": vram_gb * 1024,
                    "diskGb": disk_gb,
                    "gpuRequired": gpu_required,
                },
                "recommended": {
                    "cpuCores": cpu_cores + 4,
                    "ramMb": ram_gb * 2048,
                    "vramMb": vram_gb * 2048,
                    "diskGb": round(disk_gb * 1.8),
                    "gpuRequired": gpu_required,
                },
            },
            "editableConfig": {
                "profile": profile,
                "branch": branch,
                "port": port,
                "installDirectory": f"D:/AIHub/providers/{provider_id}",
            },
            "lastBenchmark": {
                "headlineMetric": headline,
                "secondaryMetric": secondary,
                "latencyMs": latency_ms,
                "throughput": throughput,
                "vramPeakMb": vram_peak_mb,
                "measuredAt": "2026-05-10T09:12:00.000Z",
            },
            "lastRunAt": "2026-05-10T09:12:00.000Z",
            "runtime": {
                "defaultPort": port,
                "healthUrl": f"http://localhost:{port}/health",
                "metricsUrl": f"http://localhost:{port}/metrics",
            },
            "commands": {
                "windows": {
                    "setup": "scripts/windows/setup.ps1",
                    "run": "scripts/windows/run.ps1",
                    "stop": "scripts/windows/stop.ps1",
                    "health": "scripts/windows/health.ps1",
                    "metrics": "scripts/windows/collect-metrics.ps1",
                },
                "linux": {
                    "setup": "scripts/linux/setup.sh",
                    "run": "scripts/linux/run.sh",
                    "stop": "scripts/linux/stop.sh",
                    "health": "scripts/linux/health.sh",
                    "metrics": "scripts/linux/collect-metrics.sh",
                },
            },
        }
        provider_data = cast(dict[str, Any], provider)
        requirements = cast(dict[str, Any], provider_data["requirements"])
        provider_data["compatibility"] = evaluate_compatibility(
            hardware,
            requirements["minimum"],
            requirements["recommended"],
        )
        providers.append(provider)

    return deepcopy(providers)


RUNNING_TASKS = [
    {
        "id": "task-llm-chat",
        "projectId": "local-llm-studio",
        "projectName": "Local LLM Studio",
        "type": "llm",
        "status": "running",
        "startedAt": "2026-05-10T09:42:00.000Z",
        "durationSec": 3120,
        "cpuPercent": 18,
        "gpuPercent": 42,
        "ramMb": 9140,
        "vramMb": 12680,
        "currentStep": "Serving chat endpoint",
        "progressPercent": 100,
    }
]
